### ISSUE TITLE
update acknowledgments 

### ISSUE THREAD

**Issue by kaiemjoy** [UCD-SEG/serocalculator#100]
Acknowledge all SEES sites in the enteric fever vignette

**Comment by kristinawlai** [comment]
@kaiemjoy Here's what I have... is it also Ghana? "Special thanks to our collaborators at Aga Khan University  (Karachi, Pakistan), Child Health Research Foundation (Dhaka, Bangladesh), and Dhulikhel Hospital, Kathmandu University Hospital (Dhulikhel, Nepal)."

**Comment by kaiemjoy** [comment]
Yes, that's perfect. I don't think the Ghana data is in there yet. is that right?

**Comment by kristinawlai** [comment]
Yes that's correct! This and some other small edits were added in the last PR #93 so it's not merged into main just yet.
