### ISSUE TITLE
age case in clean_pop_data

### ISSUE THREAD

**Issue by kaiemjoy** [UCD-SEG/serocalculator#104]
we should allow age to be called Age or age (ignore case)

**Comment by kaiemjoy** [comment]
the problem is clean_pop_data seems to expect age to come in with a capital A and throws an error if its lowercase

**Comment by kaiemjoy** [comment]
> xs_data <- raw_xs_data %>% 
+   filter(study == "SEES") %>%
+   select(index_id, country, catchment, age, result) %>%
+   clean_pop_data()
Error in `.data$Age`:
! Column `Age` not found in `.data`.
Backtrace:
  1. ... %>% clean_pop_data()
 21. rlang:::abort_data_pronoun(x, call = y)

**Comment by kaiemjoy** [comment]
let's add an argument to clean_pop_data to specify the name of the age variable and the result variable like this clean_pop_data(age_var = c("age"), result_var=c("result))

**Comment by kaiemjoy** [comment]
first try automatically to search for "age" and "Age"

**Comment by chrisorwa** [comment]
@kaiemjoy searching for column(s) with "age" or "Age" works. The result of the search to be stored in pop_data class attribute referred to as `age_var`.
