### ISSUE TITLE
upgrade API messages to `cli`

### ISSUE THREAD

**Issue by d-morrison** [UCD-SEG/serocalculator#108]
- [x] Replace all `stop()` calls with `cli::cli_abort()`
- [x] Replace all `warning()` calls with `cli::cli_warn()`
- [x] Replace all `message()` calls with `cli::cli_inform()`

**Comment by chrisorwa** [comment]
Please review the issue @d-morrison

**Comment by chrisorwa** [comment]
Implemented and merged.
