### ISSUE TITLE
Rename functions using tidyverse conventions and create aliases

### ISSUE THREAD

**Issue by chrisorwa** [UCD-SEG/serocalculator#111]
Create alias for functions that don't follow tidyverse function naming convention

**Comment by d-morrison** [comment]
@chrisorwa I finally had time to track down the recommended method for renaming functions:

https://lifecycle.r-lib.org/articles/communicate.html#rename-a-function

Please follow the instructions on that page to complete this issue; we can discuss tomorrow!

**Comment by d-morrison** [comment]
> @chrisorwa I finally had time to track down the recommended method for renaming functions:
> 
> https://lifecycle.r-lib.org/articles/communicate.html#rename-a-function
> 
> Please follow the instructions on that page to complete this issue; we can discuss tomorrow!

PS - just to clarify, these instructions remove the need for `@rdname` or `@alias` tags
