### ISSUE TITLE
add group_by option to summary() for class pop_data 

### ISSUE THREAD

**Issue by kaiemjoy** [UCD-SEG/serocalculator#112]
summary.pop_data()

**Comment by kaiemjoy** [comment]
Id' like to add an option to summary() for objects with class pop_data to summarize by a stratifying variable/grou_by() (like country). Right now summary is not working at all though: 
> xs_data <- 
+   "https://osf.io/download//n6cp3/" %>% 
+   load_pop_data()
> View(xs_data)
> summary(xs_data)
Error in `distinct()`:
! Must use existing variables.
✖ `id` not found in `.data`.
✖ `age` not found in `.data`.

**Comment by kaiemjoy** [comment]
something like: 

summary(xs_data, strata = c("Country"))

**Comment by d-morrison** [comment]
@kaiemjoy this option has been implemented by @chrisorwa; please see example [here](https://ucd-serg.github.io/serocalculator/reference/summary.pop_data.html#ref-examples). Please test it out? If it meets your expectations, we can close this issue.

**Comment by chrisorwa** [comment]
Implemented and merged.
