### ISSUE TITLE
Add user error message for missing strata

### ISSUE THREAD

**Issue by kristinawlai** [UCD-SEG/serocalculator#224]
Add a user error message that alerts user of missing data in strata variable for est.incidence.by(). Would it make sense to add functionality to exclude rows with missing strata, but still allow it to run? Current error is below in an example stratifying on district: 

![image](https://github.com/user-attachments/assets/3c20e994-3f20-4f21-b200-b2ff60429784)

**Comment by kristinawlai** [comment]
@kaiemjoy, after you left today's call we discussed this issue of how to handle missing values in strata variables for `est.incidence.by()`. We came up with 3 options: 
1. Run the estimates, but automatically exclude NAs and produce a warning message that indicates there were X (xx%) missing values within the strata variable, and prompt the user to make sure that is expected. As a reminder, we discussed this last week and noted that users might just run the estimates without reading the warning messages. 
2. Don't run the estimates and produce an error message that indicates there were X (xx%) missing values within the strata variable, and prompt the user to remove or recategorize the missing values before attempting to calculate the estimates again. 
3. Run the estimates and automatically create an additional strata level for the missing values. (Ezra mentioned that the user could do this themselves if they want and that we may not want to assume what the user wants to do)

On the call, the rest of us were preferring option 1, but we really wanted your input. What do you think?

**Comment by kristinawlai** [comment]
@chrisorwa I haven't been able to replicate the same errors I was getting previously (on my desktop or in Posit), so maybe some of your prior updates have already fixed it. `est.incidence.by()` seems to already create a separate strata and reports an incidence estimate for NAs as well as each level of the strata variable. We can see what @kaiemjoy thinks is the preferred action. I will continue to play with the unpublished dataset that I'm not able to share to see if I can figure out what the difference is. 

![image](https://github.com/user-attachments/assets/f86764ac-7ea4-477d-a5e2-53bce27f9779)

**Comment by chrisorwa** [comment]
Thanks @kristinawlai

**Comment by d-morrison** [comment]
> @chrisorwa I haven't been able to replicate the same errors I was getting previously (on my desktop or in Posit), so maybe some of your prior updates have already fixed it. `est.incidence.by()` seems to already create a separate strata and reports an incidence estimate for NAs as well as each level of the strata variable. We can see what @kaiemjoy thinks is the preferred action. I will continue to play with the unpublished dataset that I'm not able to share to see if I can figure out what the difference is.
> 
> ![image](https://private-user-images.githubusercontent.com/57973437/357598270-f86764ac-7ea4-477d-a5e2-53bce27f9779.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MzM0MzcsIm5iZiI6MTczMDgzMzEzNywicGF0aCI6Ii81Nzk3MzQzNy8zNTc1OTgyNzAtZjg2NzY0YWMtN2VhNC00NzdkLWE1ZTItNTNiY2UyN2Y5Nzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE4NTg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMjRhOWY5OTU2ZjVjMDg2NGE0NGRjYWI0Y2UzNTI4ZTlkNWE0MjczZTJmMDA5NWU1NDYzODYwZDNhZWU2NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.po1anRitWrCGMsL-63fFLtUFT5itBexVA5dJ17t1GpY)

@kristinawlai can we close this issue as completed?
