### ISSUE TITLE
pop age match with words that end with age like "village"

### ISSUE THREAD

**Issue by kaiemjoy** [UCD-SEG/serocalculator#233]
> ##prepare cross-sectional data 
> xs_data <- 
+   data %>% 
+   as_pop_data() 
Error in `set_value()`:
! No similar column name was detected.
Run `rlang::last_trace()` to see where the error occurred.
Warning messages:
1: Unknown or uninitialised column: `antigen_iso`. 
2: The specified `age` column "Age" does not exist. 
3: Multiple potential matches found: `Village` and `age.at.the.visit` 
4: Using first match: `Village` 
5: The specified `value` column "`result`" does not exist.

**Comment by d-morrison** [comment]
current behavior (report all potential matches, use left-most in dataset) will stay for now.
