### ISSUE TITLE
Shiny app for decay curve model

### ISSUE THREAD

**Issue by d-morrison** [UCD-SEG/serocalculator#72]
We want to build an app that takes the 5 curve parameters as inputs and runs `autoplot.curve_params()`

- [ ] $y_0 < 1000$
- [ ] $t_1 < 100$
- [ ] label `alpha` as "(in days)"

**Comment by kristinawlai** [comment]
Vision: An app that has 5 sliders for y0, y1, t1, alpha, and r for the decay curve so the app will redraw the single curve as a teaching tool. Scaled by min and max for y1 in all of mcmc samples.

**Comment by kristinawlai** [comment]
Rough sketch: 
<img width="269" alt="image" src="https://github.com/UCD-SERG/serocalculator/assets/57973437/1d59a70d-1c35-40ad-8f4e-e65d86d60fa4">

**Comment by chrisorwa** [comment]
@d-morrison I need a quick explanation on how the curve is generated.  The code has a Markov Chain Monte Carlo file with the  y0,y1,t1,alpha and r values which are utilized to generate the elisa units. It takes a while for the code to run and generate the graph. In addition, I'd like to know how the selection of the five values fit into the code.

**Comment by d-morrison** [comment]
@chrisorwa please take a look at https://github.com/UCD-SERG/serocalculator/pull/80; I've simplified the relevant code a bit. In the shiny app, the user inputs should take the place of the MCMC file; in other words, we should use the inputs to construct a 1-row `data.frame` and pass that to `plot_curve_params_one_ab()`.

**Comment by chrisorwa** [comment]
Thanks @d-morrison.

**Comment by chrisorwa** [comment]
- Look into the issue of omitted rows. 
- Check into log transformation of zero
- Change y axis to log scale

**Comment by kaiemjoy** [comment]
- Make increments of y0 smaller from 0,1,2,3,4,5,6
 - sliders on log scale
 - check why early growth is not showing, is this an issue of log transforming 0 ??? - for the situation when baseline response is low like 0.5 or 0

**Comment by chrisorwa** [comment]
Hi @kaiemjoy I have made the changes. However, the early growth is still not showing.
