### ISSUE TITLE
Change title of curve parameters shiny app

### ISSUE THREAD

**Issue by d-morrison** [UCD-SEG/serocalculator#96]
Currently it's called "Parameters"; maybe "Serocalculator: Interactive Antibody Decay Curve Model"? @kaiemjoy @kristinawlai amu suggestions?

![image](https://github.com/UCD-SERG/serocalculator/assets/2474437/37799f00-263e-4fde-a372-22aad3479f76)

**Comment by kaiemjoy** [comment]
Serocalculator: Interactive Antibody Kinetic Model

(because we have both growth and decay)
