### ISSUE TITLE
increase number of plot points in shiny curve app

### ISSUE THREAD

**Issue by d-morrison** [UCD-SEG/serocalculator#97]
in `geom_function()`, there is an argument `n` (default 101; see https://ggplot2.tidyverse.org/reference/geom_function.html) that we should increase to 1001, or maybe 10001 (as large as possible without slowing down the app noticeably)

**Comment by chrisorwa** [comment]
Increasing the n parameter from 101 to 1001 in the `geom_function` actually makes the growth phase steeper _(if not straight)_

![Image](https://github.com/UCD-SERG/serocalculator/assets/731279/6ab1321e-1cba-484a-b821-ebcae46fba36)
